# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    packageType: 'sdk'
    version: 3.1.100
- script: dotnet publish -c $(buildConfiguration) -o out-linux -r linux-x64
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@0
  displayName: build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '-c $(buildConfiguration) -o out-linux -r linux-x64'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(system.DefaultWorkingDirectory)'
    Contents: '**'
    TargetFolder: '$(build.ArtifactStagingDirectory)'
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master')) 

- task: ado-discord-webhook@1
  inputs:
    channelId: '$(webHookChannelId)'
    webhookKey: '$(webHookKey)'
    messageType: 'embeds'
    embeds: |
      {
        "embeds": [
          {
            "description": "Build [$(Build.BuildId)]($(Build.BuildUri)) succeeded",
            "color": 631111,
          "fields": [
            {
              "name": "Requested by",
              "value": "$(Build.RequestedFor)",
              "inline": true
            },
            {
              "name": "Build pipeline",
              "value": "$(Build.DefinitionName)",
              "inline": true
            }
          ]
          }
        ]
      }